In [3]:
import numpy as np
import pandas as pd

In [5]:
data={
'date':pd.date_range('2023-01-01',periods=20),
'Product':['A','B','C','D'] *5,
'Region':['East','west','North','south','East','west','North','south','East','west','North','south',
          'East','west','North','south','East','west','North','south'],
'sales':np.random.randint(100,1000,20),
'unit':np.random.randint(10,100,20),
'Rep':['john','mary','bob','Alice','john','mary','bob','Alice','john','mary','bob','Alice',
       'john','mary','bob','Alice','john','mary','bob','Alice']
}
df=pd.DataFrame(data)
df['month']=df['date'].dt.month_name()
df['Quarter']='Q' + df['date'].dt.quarter.astype(str)
df

         date Product Region  sales  unit    Rep    month Quarter
0  2023-01-01       A   East    939    47   john  January      Q1
1  2023-01-02       B   west    781    96   mary  January      Q1
2  2023-01-03       C  North    318    46    bob  January      Q1
3  2023-01-04       D  south    904    62  Alice  January      Q1
4  2023-01-05       A   East    622    74   john  January      Q1
5  2023-01-06       B   west    482    28   mary  January      Q1
6  2023-01-07       C  North    986    52    bob  January      Q1
7  2023-01-08       D  south    732    80  Alice  January      Q1
8  2023-01-09       A   East    442    77   john  January      Q1
9  2023-01-10       B   west    180    39   mary  January      Q1
10 2023-01-11       C  North    355    32    bob  January      Q1
11 2023-01-12       D  south    161    57  Alice  January      Q1
12 2023-01-13       A   East    955    26   john  January      Q1
13 2023-01-14       B   west    813    44   mary  January      Q1
14 2023-01-15       C  North    853    76    bob  January      Q1
15 2023-01-16       D  south    714    22  Alice  January      Q1
16 2023-01-17       A   East    508    43   john  January      Q1
17 2023-01-18       B   west    149    85   mary  January      Q1
18 2023-01-19       C  North    581    51    bob  January      Q1
19 2023-01-20       D  south    114    34  Alice  January      Q1

In [9]:
pd.pivot_table(df,values='sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     622.0    NaN    NaN    NaN
North      NaN    NaN  581.0    NaN
south      NaN    NaN    NaN  714.0
west       NaN  482.0    NaN    NaN

In [14]:
pivot2=pd.pivot_table(df, values=['sales','unit'],index='Region',columns='Product')
pivot2

         sales                       unit
Product      A      B      C      D     A     B     C     D
Region
East     693.2    NaN    NaN    NaN  53.4   NaN   NaN   NaN
North      NaN    NaN  618.6    NaN   NaN   NaN  51.4   NaN
south      NaN    NaN    NaN  525.0   NaN   NaN   NaN  51.0
west       NaN  481.0    NaN    NaN   NaN  58.4   NaN   NaN

In [16]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
south    0  0  0  5
west     0  5  0  0